language: python
python:
  - "3.6"
node_js:
  - "10.9.0"
install:
  - pip install -r requirements.txt
  - cd src
  - npm install

script:
- cd src
- python manage.py collectstatic --noinput
- npm run dev
- python manage.py test